// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package nano_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// * Returns a list of block hashes which have not yet been received by these accounts
type ReqAccountPending struct {
	// * List of accounts to query
	Accounts []string `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// * Maximum number of blocks to return
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// * If true, include source account
	Source bool `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	// * Optional threshold. Returns a list of pending block hashes with amount more or equal to the threshold.
	Threshold            *wrappers.StringValue `protobuf:"bytes,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReqAccountPending) Reset()         { *m = ReqAccountPending{} }
func (m *ReqAccountPending) String() string { return proto.CompactTextString(m) }
func (*ReqAccountPending) ProtoMessage()    {}
func (*ReqAccountPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_780ec51937988978, []int{0}
}
func (m *ReqAccountPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAccountPending.Unmarshal(m, b)
}
func (m *ReqAccountPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAccountPending.Marshal(b, m, deterministic)
}
func (dst *ReqAccountPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAccountPending.Merge(dst, src)
}
func (m *ReqAccountPending) XXX_Size() int {
	return xxx_messageInfo_ReqAccountPending.Size(m)
}
func (m *ReqAccountPending) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAccountPending.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAccountPending proto.InternalMessageInfo

func (m *ReqAccountPending) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *ReqAccountPending) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqAccountPending) GetSource() bool {
	if m != nil {
		return m.Source
	}
	return false
}

func (m *ReqAccountPending) GetThreshold() *wrappers.StringValue {
	if m != nil {
		return m.Threshold
	}
	return nil
}

// * account_pending result
type ResAccountPending struct {
	// * List of accounts, each with a list of pending blocks
	Pending              []*AccountPending `protobuf:"bytes,1,rep,name=pending,proto3" json:"pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResAccountPending) Reset()         { *m = ResAccountPending{} }
func (m *ResAccountPending) String() string { return proto.CompactTextString(m) }
func (*ResAccountPending) ProtoMessage()    {}
func (*ResAccountPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_780ec51937988978, []int{1}
}
func (m *ResAccountPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResAccountPending.Unmarshal(m, b)
}
func (m *ResAccountPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResAccountPending.Marshal(b, m, deterministic)
}
func (dst *ResAccountPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResAccountPending.Merge(dst, src)
}
func (m *ResAccountPending) XXX_Size() int {
	return xxx_messageInfo_ResAccountPending.Size(m)
}
func (m *ResAccountPending) XXX_DiscardUnknown() {
	xxx_messageInfo_ResAccountPending.DiscardUnknown(m)
}

var xxx_messageInfo_ResAccountPending proto.InternalMessageInfo

func (m *ResAccountPending) GetPending() []*AccountPending {
	if m != nil {
		return m.Pending
	}
	return nil
}

// * Blocks per account
type AccountPending struct {
	// * The account
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// * List of blocks with details
	BlockInfo            []*AccountPendingBlockInfo `protobuf:"bytes,2,rep,name=block_info,json=blockInfo,proto3" json:"block_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AccountPending) Reset()         { *m = AccountPending{} }
func (m *AccountPending) String() string { return proto.CompactTextString(m) }
func (*AccountPending) ProtoMessage()    {}
func (*AccountPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_780ec51937988978, []int{2}
}
func (m *AccountPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPending.Unmarshal(m, b)
}
func (m *AccountPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPending.Marshal(b, m, deterministic)
}
func (dst *AccountPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPending.Merge(dst, src)
}
func (m *AccountPending) XXX_Size() int {
	return xxx_messageInfo_AccountPending.Size(m)
}
func (m *AccountPending) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPending.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPending proto.InternalMessageInfo

func (m *AccountPending) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountPending) GetBlockInfo() []*AccountPendingBlockInfo {
	if m != nil {
		return m.BlockInfo
	}
	return nil
}

// * Information supplied for each account in req_account_pending
type AccountPendingBlockInfo struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountPendingBlockInfo) Reset()         { *m = AccountPendingBlockInfo{} }
func (m *AccountPendingBlockInfo) String() string { return proto.CompactTextString(m) }
func (*AccountPendingBlockInfo) ProtoMessage()    {}
func (*AccountPendingBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_780ec51937988978, []int{3}
}
func (m *AccountPendingBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPendingBlockInfo.Unmarshal(m, b)
}
func (m *AccountPendingBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPendingBlockInfo.Marshal(b, m, deterministic)
}
func (dst *AccountPendingBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPendingBlockInfo.Merge(dst, src)
}
func (m *AccountPendingBlockInfo) XXX_Size() int {
	return xxx_messageInfo_AccountPendingBlockInfo.Size(m)
}
func (m *AccountPendingBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPendingBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPendingBlockInfo proto.InternalMessageInfo

func (m *AccountPendingBlockInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *AccountPendingBlockInfo) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *AccountPendingBlockInfo) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqAccountPending)(nil), "nano.api.req_account_pending")
	proto.RegisterType((*ResAccountPending)(nil), "nano.api.res_account_pending")
	proto.RegisterType((*AccountPending)(nil), "nano.api.account_pending")
	proto.RegisterType((*AccountPendingBlockInfo)(nil), "nano.api.account_pending_block_info")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_accounts_780ec51937988978) }

var fileDescriptor_accounts_780ec51937988978 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0xc9, 0x36, 0xb7, 0xe5, 0x3b, 0x50, 0x88, 0x22, 0xb1, 0x88, 0x94, 0xe2, 0xa1, 0xa7,
	0x0c, 0xb6, 0x9b, 0x57, 0x4f, 0x7a, 0x8c, 0xe0, 0xb5, 0xa6, 0x5d, 0xfa, 0x03, 0x6b, 0x12, 0xd3,
	0x16, 0xff, 0x18, 0xff, 0x59, 0x59, 0x96, 0x6c, 0x50, 0xd9, 0xed, 0xbd, 0xf0, 0xe1, 0xfb, 0x5e,
	0x1e, 0x5c, 0x8a, 0xa2, 0xd0, 0x83, 0xea, 0x3b, 0x66, 0xac, 0xee, 0x35, 0x59, 0x2a, 0xa1, 0x34,
	0x13, 0xa6, 0x89, 0x1e, 0x2a, 0xad, 0xab, 0x56, 0xae, 0xdd, 0x7b, 0x3e, 0x94, 0xeb, 0x1f, 0x2b,
	0x8c, 0x91, 0xd6, 0x93, 0xc9, 0x2f, 0x82, 0x6b, 0x2b, 0xbf, 0x33, 0x7f, 0x20, 0x33, 0x52, 0xed,
	0x1a, 0x55, 0x91, 0x08, 0x96, 0xe1, 0x26, 0x45, 0xf1, 0x34, 0xc5, 0xfc, 0xe8, 0xc9, 0x0d, 0x5c,
	0x38, 0x45, 0x27, 0x31, 0x4a, 0x67, 0xfc, 0x60, 0xc8, 0x2d, 0xcc, 0x3b, 0x3d, 0xd8, 0x42, 0xd2,
	0x69, 0x8c, 0xd2, 0x25, 0xf7, 0x8e, 0x3c, 0x01, 0xee, 0x6b, 0x2b, 0xbb, 0x5a, 0xb7, 0x3b, 0x3a,
	0x8b, 0x51, 0xba, 0xda, 0xdc, 0xb3, 0x43, 0x2b, 0x16, 0x5a, 0xb1, 0xb7, 0xde, 0x36, 0xaa, 0x7a,
	0x17, 0xed, 0x20, 0xf9, 0x09, 0x4f, 0x5e, 0xf7, 0xe5, 0xba, 0x7f, 0xe5, 0xb6, 0xb0, 0xf0, 0xd2,
	0x75, 0x5b, 0x6d, 0xee, 0x58, 0xf8, 0x30, 0x1b, 0xb1, 0x3c, 0x90, 0x89, 0x81, 0xab, 0xf1, 0x1d,
	0x0a, 0x0b, 0xff, 0x44, 0x51, 0x8c, 0x52, 0xcc, 0x83, 0x25, 0xcf, 0x00, 0x79, 0xab, 0x8b, 0xcf,
	0xac, 0x51, 0xa5, 0xa6, 0x13, 0x17, 0xf2, 0x78, 0x36, 0x24, 0x3b, 0xb1, 0x1c, 0x3b, 0xfd, 0xa2,
	0x4a, 0x9d, 0x7c, 0x40, 0x74, 0x1e, 0x24, 0x04, 0x66, 0xb5, 0xe8, 0x6a, 0x9f, 0xec, 0xf4, 0x7e,
	0x43, 0xf1, 0x75, 0x9c, 0x16, 0x73, 0xef, 0x46, 0xdb, 0xe2, 0xb0, 0x6d, 0x3e, 0x77, 0x03, 0x6e,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xef, 0x2a, 0x31, 0xeb, 0x00, 0x02, 0x00, 0x00,
}
