// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package nano_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// API versions. proto3 doesn't have constants, so we use an enum
// which allows aliases. VERSION_INVALID is a 0-value placeholder, which
// protobuf requires.
type APIVersion int32

const (
	APIVersion_VERSION_INVALID APIVersion = 0
	APIVersion_VERSION_MAJOR   APIVersion = 1
	APIVersion_VERSION_MINOR   APIVersion = 0
)

var APIVersion_name = map[int32]string{
	0: "VERSION_INVALID",
	1: "VERSION_MAJOR",
	// Duplicate value: 0: "VERSION_MINOR",
}
var APIVersion_value = map[string]int32{
	"VERSION_INVALID": 0,
	"VERSION_MAJOR":   1,
	"VERSION_MINOR":   0,
}

func (x APIVersion) String() string {
	return proto.EnumName(APIVersion_name, int32(x))
}
func (APIVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{0}
}

// *
// The request type enum values must NOT change. The name of the enum must match
// the request message name, uppercased, and without the req_ prefix. This naming
// standard facilitates dynamic lookup and generic frameworks.
type RequestType int32

const (
	RequestType_INVALID           RequestType = 0
	RequestType_REGISTER_CALLBACK RequestType = 1
	// core.proto message types
	RequestType_PING                RequestType = 2
	RequestType_ACCOUNT_BALANCE     RequestType = 3
	RequestType_ACCOUNT_BLOCK_COUNT RequestType = 4
	RequestType_ACCOUNT_PENDING     RequestType = 5
	// util.proto message types
	RequestType_ADDRESS_VALID RequestType = 1000
)

var RequestType_name = map[int32]string{
	0:    "INVALID",
	1:    "REGISTER_CALLBACK",
	2:    "PING",
	3:    "ACCOUNT_BALANCE",
	4:    "ACCOUNT_BLOCK_COUNT",
	5:    "ACCOUNT_PENDING",
	1000: "ADDRESS_VALID",
}
var RequestType_value = map[string]int32{
	"INVALID":             0,
	"REGISTER_CALLBACK":   1,
	"PING":                2,
	"ACCOUNT_BALANCE":     3,
	"ACCOUNT_BLOCK_COUNT": 4,
	"ACCOUNT_PENDING":     5,
	"ADDRESS_VALID":       1000,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{1}
}

// *
// Request header.
// This is serialized before the actual request to tell the node what message to expect next.
// Other request meta data may be added in the future.
type Request struct {
	// * Request type
	Type                 RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=nano.api.RequestType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() RequestType {
	if m != nil {
		return m.Type
	}
	return RequestType_INVALID
}

// *
// Response header.
// This is serialized before the actual response.
type Response struct {
	// *
	// For which request type is this a response? This flag allows future support for clients
	// issuing multiple concurrent requests, as well as callback messages.
	//
	// This may not be set if error_code is non-zero.
	Type RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=nano.api.RequestType" json:"type,omitempty"`
	// *
	// Context dependent error code. For instance, if IO_ERROR occurs, the error_code
	// may contain a more specific, system depended error code.
	ErrorCode int32 `protobuf:"zigzag32,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// * Error message. Only set if error_code is non-zero.
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// * Error category name. Only set if error_code is non-zero.
	ErrorCategory        string   `protobuf:"bytes,4,opt,name=error_category,json=errorCategory,proto3" json:"error_category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() RequestType {
	if m != nil {
		return m.Type
	}
	return RequestType_INVALID
}

func (m *Response) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Response) GetErrorCategory() string {
	if m != nil {
		return m.ErrorCategory
	}
	return ""
}

// * Send ping to the node
type ReqPing struct {
	// * Ping ID. The node will respond with the same ID.
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPing) Reset()         { *m = ReqPing{} }
func (m *ReqPing) String() string { return proto.CompactTextString(m) }
func (*ReqPing) ProtoMessage()    {}
func (*ReqPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{2}
}
func (m *ReqPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPing.Unmarshal(m, b)
}
func (m *ReqPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPing.Marshal(b, m, deterministic)
}
func (dst *ReqPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPing.Merge(dst, src)
}
func (m *ReqPing) XXX_Size() int {
	return xxx_messageInfo_ReqPing.Size(m)
}
func (m *ReqPing) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPing.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPing proto.InternalMessageInfo

func (m *ReqPing) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// * Ping response
type ResPing struct {
	// * The same ID as sent in the ping reqyest
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResPing) Reset()         { *m = ResPing{} }
func (m *ResPing) String() string { return proto.CompactTextString(m) }
func (*ResPing) ProtoMessage()    {}
func (*ResPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{3}
}
func (m *ResPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResPing.Unmarshal(m, b)
}
func (m *ResPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResPing.Marshal(b, m, deterministic)
}
func (dst *ResPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResPing.Merge(dst, src)
}
func (m *ResPing) XXX_Size() int {
	return xxx_messageInfo_ResPing.Size(m)
}
func (m *ResPing) XXX_DiscardUnknown() {
	xxx_messageInfo_ResPing.DiscardUnknown(m)
}

var xxx_messageInfo_ResPing proto.InternalMessageInfo

func (m *ResPing) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// * Returns a list of block hashes which have not yet been received by these accounts
type ReqAccountPending struct {
	// * List of accounts to query
	Accounts []string `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// * Maximum number of blocks to return
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// * If true, include source account
	Source bool `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	// * Optional threshold. Returns a list of pending block hashes with amount more or equal to the threshold.
	Threshold            *wrappers.StringValue `protobuf:"bytes,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReqAccountPending) Reset()         { *m = ReqAccountPending{} }
func (m *ReqAccountPending) String() string { return proto.CompactTextString(m) }
func (*ReqAccountPending) ProtoMessage()    {}
func (*ReqAccountPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{4}
}
func (m *ReqAccountPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAccountPending.Unmarshal(m, b)
}
func (m *ReqAccountPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAccountPending.Marshal(b, m, deterministic)
}
func (dst *ReqAccountPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAccountPending.Merge(dst, src)
}
func (m *ReqAccountPending) XXX_Size() int {
	return xxx_messageInfo_ReqAccountPending.Size(m)
}
func (m *ReqAccountPending) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAccountPending.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAccountPending proto.InternalMessageInfo

func (m *ReqAccountPending) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *ReqAccountPending) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqAccountPending) GetSource() bool {
	if m != nil {
		return m.Source
	}
	return false
}

func (m *ReqAccountPending) GetThreshold() *wrappers.StringValue {
	if m != nil {
		return m.Threshold
	}
	return nil
}

// * account_pending result
type ResAccountPending struct {
	// * List of accounts, each with a list of pending blocks
	Pending              []*AccountPending `protobuf:"bytes,1,rep,name=pending,proto3" json:"pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResAccountPending) Reset()         { *m = ResAccountPending{} }
func (m *ResAccountPending) String() string { return proto.CompactTextString(m) }
func (*ResAccountPending) ProtoMessage()    {}
func (*ResAccountPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{5}
}
func (m *ResAccountPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResAccountPending.Unmarshal(m, b)
}
func (m *ResAccountPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResAccountPending.Marshal(b, m, deterministic)
}
func (dst *ResAccountPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResAccountPending.Merge(dst, src)
}
func (m *ResAccountPending) XXX_Size() int {
	return xxx_messageInfo_ResAccountPending.Size(m)
}
func (m *ResAccountPending) XXX_DiscardUnknown() {
	xxx_messageInfo_ResAccountPending.DiscardUnknown(m)
}

var xxx_messageInfo_ResAccountPending proto.InternalMessageInfo

func (m *ResAccountPending) GetPending() []*AccountPending {
	if m != nil {
		return m.Pending
	}
	return nil
}

// * Blocks per account
type AccountPending struct {
	// * The account
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// * List of blocks with details
	BlockInfo            []*AccountPendingBlockInfo `protobuf:"bytes,2,rep,name=block_info,json=blockInfo,proto3" json:"block_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AccountPending) Reset()         { *m = AccountPending{} }
func (m *AccountPending) String() string { return proto.CompactTextString(m) }
func (*AccountPending) ProtoMessage()    {}
func (*AccountPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{6}
}
func (m *AccountPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPending.Unmarshal(m, b)
}
func (m *AccountPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPending.Marshal(b, m, deterministic)
}
func (dst *AccountPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPending.Merge(dst, src)
}
func (m *AccountPending) XXX_Size() int {
	return xxx_messageInfo_AccountPending.Size(m)
}
func (m *AccountPending) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPending.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPending proto.InternalMessageInfo

func (m *AccountPending) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountPending) GetBlockInfo() []*AccountPendingBlockInfo {
	if m != nil {
		return m.BlockInfo
	}
	return nil
}

// * Information supplied for each account in req_account_pending
type AccountPendingBlockInfo struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountPendingBlockInfo) Reset()         { *m = AccountPendingBlockInfo{} }
func (m *AccountPendingBlockInfo) String() string { return proto.CompactTextString(m) }
func (*AccountPendingBlockInfo) ProtoMessage()    {}
func (*AccountPendingBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_67089c3a2e11cb81, []int{7}
}
func (m *AccountPendingBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPendingBlockInfo.Unmarshal(m, b)
}
func (m *AccountPendingBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPendingBlockInfo.Marshal(b, m, deterministic)
}
func (dst *AccountPendingBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPendingBlockInfo.Merge(dst, src)
}
func (m *AccountPendingBlockInfo) XXX_Size() int {
	return xxx_messageInfo_AccountPendingBlockInfo.Size(m)
}
func (m *AccountPendingBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPendingBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPendingBlockInfo proto.InternalMessageInfo

func (m *AccountPendingBlockInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *AccountPendingBlockInfo) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *AccountPendingBlockInfo) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "nano.api.request")
	proto.RegisterType((*Response)(nil), "nano.api.response")
	proto.RegisterType((*ReqPing)(nil), "nano.api.req_ping")
	proto.RegisterType((*ResPing)(nil), "nano.api.res_ping")
	proto.RegisterType((*ReqAccountPending)(nil), "nano.api.req_account_pending")
	proto.RegisterType((*ResAccountPending)(nil), "nano.api.res_account_pending")
	proto.RegisterType((*AccountPending)(nil), "nano.api.account_pending")
	proto.RegisterType((*AccountPendingBlockInfo)(nil), "nano.api.account_pending_block_info")
	proto.RegisterEnum("nano.api.APIVersion", APIVersion_name, APIVersion_value)
	proto.RegisterEnum("nano.api.RequestType", RequestType_name, RequestType_value)
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_core_67089c3a2e11cb81) }

var fileDescriptor_core_67089c3a2e11cb81 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0x9b, 0x4c,
	0x10, 0xc7, 0x03, 0x21, 0xb1, 0x19, 0x7f, 0x4e, 0xc8, 0xe6, 0x4b, 0x4b, 0xad, 0xb6, 0xb2, 0x68,
	0x2b, 0xb9, 0x39, 0x10, 0x29, 0xe9, 0xa9, 0x37, 0x82, 0x51, 0x44, 0xe2, 0xe0, 0x68, 0xed, 0xfa,
	0x4a, 0x31, 0xac, 0x31, 0xaa, 0xc3, 0x92, 0x5d, 0xac, 0xca, 0xaf, 0xd1, 0x6b, 0x2f, 0x7d, 0xbc,
	0x3e, 0x46, 0xc5, 0x02, 0x76, 0xea, 0x36, 0x87, 0xde, 0x66, 0xfe, 0xfb, 0xdb, 0x99, 0xff, 0xce,
	0x2c, 0x40, 0x48, 0x19, 0x31, 0x33, 0x46, 0x73, 0x8a, 0x9a, 0x69, 0x90, 0x52, 0x33, 0xc8, 0x92,
	0xce, 0xeb, 0x98, 0xd2, 0x78, 0x41, 0xce, 0x84, 0x3e, 0x5d, 0xce, 0xce, 0xbe, 0xb2, 0x20, 0xcb,
	0x08, 0xe3, 0x25, 0x69, 0x7c, 0x80, 0x06, 0x23, 0x0f, 0x4b, 0xc2, 0x73, 0xf4, 0x1e, 0x94, 0x7c,
	0x95, 0x11, 0x5d, 0xea, 0x4a, 0xbd, 0x83, 0xf3, 0x13, 0xb3, 0xae, 0x61, 0xe2, 0x12, 0x18, 0xaf,
	0x32, 0x82, 0x05, 0x62, 0xfc, 0x90, 0xa0, 0xc9, 0x08, 0xcf, 0x68, 0xca, 0xc9, 0x3f, 0xdc, 0x43,
	0xaf, 0x00, 0x08, 0x63, 0x94, 0xf9, 0x21, 0x8d, 0x88, 0x2e, 0x77, 0xa5, 0xde, 0x11, 0x56, 0x85,
	0x62, 0xd3, 0x88, 0xa0, 0x37, 0xd0, 0x2e, 0x8f, 0xef, 0x09, 0xe7, 0x41, 0x4c, 0xf4, 0xdd, 0xae,
	0xd4, 0x53, 0xf1, 0x7f, 0x42, 0xbc, 0x2d, 0x35, 0xf4, 0x0e, 0x0e, 0xaa, 0x1a, 0x41, 0x4e, 0x62,
	0xca, 0x56, 0xba, 0x22, 0xa8, 0xf2, 0xaa, 0x5d, 0x89, 0x46, 0xa7, 0x70, 0xf8, 0xe0, 0x67, 0x49,
	0x1a, 0xa3, 0x03, 0x90, 0x93, 0x48, 0xf8, 0x6b, 0x63, 0x39, 0x89, 0xca, 0x33, 0xfe, 0xf7, 0xb3,
	0xef, 0x12, 0x1c, 0x17, 0x17, 0x83, 0x30, 0xa4, 0xcb, 0x34, 0xf7, 0x33, 0x92, 0x46, 0x05, 0xd7,
	0x81, 0x66, 0x25, 0x71, 0x5d, 0xea, 0xee, 0xf6, 0x54, 0xbc, 0xce, 0xd1, 0xff, 0xb0, 0x27, 0x22,
	0xf1, 0x22, 0x05, 0x97, 0x09, 0x7a, 0x06, 0xfb, 0x9c, 0x2e, 0x59, 0x58, 0x3e, 0xa3, 0x89, 0xab,
	0x0c, 0x7d, 0x04, 0x35, 0x9f, 0x33, 0xc2, 0xe7, 0x74, 0x11, 0x09, 0xef, 0xad, 0xf3, 0x97, 0x66,
	0xb9, 0x26, 0xb3, 0x5e, 0x93, 0x39, 0xca, 0x59, 0x92, 0xc6, 0x93, 0x60, 0xb1, 0x24, 0x78, 0x83,
	0x1b, 0xd7, 0x85, 0x39, 0xfe, 0x87, 0xb9, 0x0b, 0x68, 0x54, 0xa1, 0xf0, 0xd6, 0x3a, 0x7f, 0xb1,
	0xd9, 0xc2, 0x16, 0x8b, 0x6b, 0xd2, 0xc8, 0xe0, 0x70, 0xbb, 0x8e, 0x0e, 0x8d, 0x4a, 0x12, 0x13,
	0x51, 0x71, 0x9d, 0x22, 0x1b, 0x60, 0xba, 0xa0, 0xe1, 0x17, 0x3f, 0x49, 0x67, 0x54, 0x97, 0x45,
	0x93, 0xb7, 0x4f, 0x36, 0xf1, 0x37, 0x2c, 0x56, 0x45, 0xec, 0xa6, 0x33, 0x6a, 0x7c, 0x86, 0xce,
	0xd3, 0x20, 0x42, 0xa0, 0xcc, 0x03, 0x3e, 0xaf, 0x3a, 0x8b, 0xb8, 0x98, 0x61, 0x70, 0xbf, 0x1e,
	0xad, 0x8a, 0xab, 0x6c, 0x6b, 0xb6, 0x6a, 0x3d, 0xdb, 0xd3, 0x1b, 0x00, 0xeb, 0xce, 0x9d, 0x10,
	0xc6, 0x13, 0x9a, 0xa2, 0x63, 0x38, 0x9c, 0x38, 0x78, 0xe4, 0x0e, 0x3d, 0xdf, 0xf5, 0x26, 0xd6,
	0xc0, 0xed, 0x6b, 0x3b, 0xe8, 0x08, 0xda, 0xb5, 0x78, 0x6b, 0x5d, 0x0f, 0xb1, 0x26, 0xfd, 0x26,
	0xb9, 0xde, 0x10, 0x6b, 0x3b, 0x1d, 0x59, 0x93, 0x4e, 0xbf, 0x49, 0xd0, 0x7a, 0xf4, 0x87, 0x51,
	0x0b, 0x1a, 0x9b, 0x32, 0x27, 0x70, 0x84, 0x9d, 0x2b, 0x77, 0x34, 0x76, 0xb0, 0x6f, 0x5b, 0x83,
	0xc1, 0xa5, 0x65, 0xdf, 0x68, 0x12, 0x6a, 0x82, 0x72, 0xe7, 0x7a, 0x57, 0x9a, 0x5c, 0x34, 0xb7,
	0x6c, 0x7b, 0xf8, 0xc9, 0x1b, 0xfb, 0x97, 0xd6, 0xc0, 0xf2, 0x6c, 0x47, 0xdb, 0x45, 0xcf, 0xe1,
	0x78, 0x2d, 0x0e, 0x86, 0xf6, 0x8d, 0x2f, 0x62, 0x4d, 0x79, 0x4c, 0xdf, 0x39, 0x5e, 0xbf, 0x28,
	0xb1, 0x87, 0x10, 0xb4, 0xad, 0x7e, 0x1f, 0x3b, 0xa3, 0x91, 0x5f, 0xb6, 0xfd, 0xd9, 0x98, 0xee,
	0x8b, 0x2f, 0x72, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x0c, 0xe7, 0x9a, 0xef, 0x03, 0x00,
	0x00,
}
