// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package nano_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryType int32

const (
	QueryType_UNKOWN              QueryType = 0
	QueryType_REGISTER_CALLBACK   QueryType = 1
	QueryType_PING                QueryType = 2
	QueryType_ACCOUNT_BALANCE     QueryType = 3
	QueryType_ACCOUNT_BLOCK_COUNT QueryType = 4
	QueryType_ACCOUNT_PENDING     QueryType = 5
)

var QueryType_name = map[int32]string{
	0: "UNKOWN",
	1: "REGISTER_CALLBACK",
	2: "PING",
	3: "ACCOUNT_BALANCE",
	4: "ACCOUNT_BLOCK_COUNT",
	5: "ACCOUNT_PENDING",
}
var QueryType_value = map[string]int32{
	"UNKOWN":              0,
	"REGISTER_CALLBACK":   1,
	"PING":                2,
	"ACCOUNT_BALANCE":     3,
	"ACCOUNT_BLOCK_COUNT": 4,
	"ACCOUNT_PENDING":     5,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{0}
}

// *
// This is serialized before the actual query to tell the node what message to expect next.
// Other query meta data may be added in the future.
type Query struct {
	// * Query type
	Type                 QueryType `protobuf:"varint,1,opt,name=type,proto3,enum=nano.api.QueryType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{0}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (dst *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(dst, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_UNKOWN
}

// *
// This is serialized before the actual response.
// In the future, this will also be sent on callback connections.
type Response struct {
	// *
	// For which query type is this a response? This flag allows future support for clients
	// issuing multiple concurrent queries, as well as callback messages.
	//
	// This may not be set if error_code is non-zero.
	Type QueryType `protobuf:"varint,1,opt,name=type,proto3,enum=nano.api.QueryType" json:"type,omitempty"`
	// *
	// Context dependent error code. For instance, if IO_ERROR occurs, the error_code
	// may contain a more specific, system depended error code.
	ErrorCode int32 `protobuf:"zigzag32,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// * Error message. Only set if error_code is non-zero.
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// * Error category name. Only set if error_code is non-zero.
	ErrorCategory        string   `protobuf:"bytes,4,opt,name=error_category,json=errorCategory,proto3" json:"error_category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_UNKOWN
}

func (m *Response) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Response) GetErrorCategory() string {
	if m != nil {
		return m.ErrorCategory
	}
	return ""
}

// *
// Establish a session with the node. This is optional if the node doesn't check api keys.
// A client will typically send this if it supports multiple node or api versions.
// The node may reject clients if the version is too old.
type QueryClientConnect struct {
	// * Client's API version
	ApiVersion uint32 `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// * Printable name. This shows up in node logs.
	ApiClientId string `protobuf:"bytes,2,opt,name=api_client_id,json=apiClientId,proto3" json:"api_client_id,omitempty"`
	// * API key. The node may be configured to require this.
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryClientConnect) Reset()         { *m = QueryClientConnect{} }
func (m *QueryClientConnect) String() string { return proto.CompactTextString(m) }
func (*QueryClientConnect) ProtoMessage()    {}
func (*QueryClientConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{2}
}
func (m *QueryClientConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClientConnect.Unmarshal(m, b)
}
func (m *QueryClientConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClientConnect.Marshal(b, m, deterministic)
}
func (dst *QueryClientConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClientConnect.Merge(dst, src)
}
func (m *QueryClientConnect) XXX_Size() int {
	return xxx_messageInfo_QueryClientConnect.Size(m)
}
func (m *QueryClientConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClientConnect.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClientConnect proto.InternalMessageInfo

func (m *QueryClientConnect) GetApiVersion() uint32 {
	if m != nil {
		return m.ApiVersion
	}
	return 0
}

func (m *QueryClientConnect) GetApiClientId() string {
	if m != nil {
		return m.ApiClientId
	}
	return ""
}

func (m *QueryClientConnect) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

// * Connect response
type ResClientConnect struct {
	ApiVersion           uint32   `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	NodeVersionMajor     uint32   `protobuf:"varint,2,opt,name=node_version_major,json=nodeVersionMajor,proto3" json:"node_version_major,omitempty"`
	NodeVersionPatch     uint32   `protobuf:"varint,3,opt,name=node_version_patch,json=nodeVersionPatch,proto3" json:"node_version_patch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResClientConnect) Reset()         { *m = ResClientConnect{} }
func (m *ResClientConnect) String() string { return proto.CompactTextString(m) }
func (*ResClientConnect) ProtoMessage()    {}
func (*ResClientConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{3}
}
func (m *ResClientConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResClientConnect.Unmarshal(m, b)
}
func (m *ResClientConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResClientConnect.Marshal(b, m, deterministic)
}
func (dst *ResClientConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResClientConnect.Merge(dst, src)
}
func (m *ResClientConnect) XXX_Size() int {
	return xxx_messageInfo_ResClientConnect.Size(m)
}
func (m *ResClientConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_ResClientConnect.DiscardUnknown(m)
}

var xxx_messageInfo_ResClientConnect proto.InternalMessageInfo

func (m *ResClientConnect) GetApiVersion() uint32 {
	if m != nil {
		return m.ApiVersion
	}
	return 0
}

func (m *ResClientConnect) GetNodeVersionMajor() uint32 {
	if m != nil {
		return m.NodeVersionMajor
	}
	return 0
}

func (m *ResClientConnect) GetNodeVersionPatch() uint32 {
	if m != nil {
		return m.NodeVersionPatch
	}
	return 0
}

// * Send ping to the node
type QueryPing struct {
	// * Ping ID. The node will respond with the same ID.
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPing) Reset()         { *m = QueryPing{} }
func (m *QueryPing) String() string { return proto.CompactTextString(m) }
func (*QueryPing) ProtoMessage()    {}
func (*QueryPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{4}
}
func (m *QueryPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPing.Unmarshal(m, b)
}
func (m *QueryPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPing.Marshal(b, m, deterministic)
}
func (dst *QueryPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPing.Merge(dst, src)
}
func (m *QueryPing) XXX_Size() int {
	return xxx_messageInfo_QueryPing.Size(m)
}
func (m *QueryPing) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPing.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPing proto.InternalMessageInfo

func (m *QueryPing) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// * Ping response
type ResPing struct {
	// * The same ID as sent in the ping query
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResPing) Reset()         { *m = ResPing{} }
func (m *ResPing) String() string { return proto.CompactTextString(m) }
func (*ResPing) ProtoMessage()    {}
func (*ResPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{5}
}
func (m *ResPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResPing.Unmarshal(m, b)
}
func (m *ResPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResPing.Marshal(b, m, deterministic)
}
func (dst *ResPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResPing.Merge(dst, src)
}
func (m *ResPing) XXX_Size() int {
	return xxx_messageInfo_ResPing.Size(m)
}
func (m *ResPing) XXX_DiscardUnknown() {
	xxx_messageInfo_ResPing.DiscardUnknown(m)
}

var xxx_messageInfo_ResPing proto.InternalMessageInfo

func (m *ResPing) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// * Returns a list of block hashes which have not yet been received by these accounts
type QueryAccountPending struct {
	// * List of accounts to query
	Accounts []string `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// * Maximum number of blocks to return
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// * If true, include source account
	Source bool `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	// * Optional threshold. Returns a list of pending block hashes with amount more or equal to the threshold.
	Threshold            *wrappers.StringValue `protobuf:"bytes,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *QueryAccountPending) Reset()         { *m = QueryAccountPending{} }
func (m *QueryAccountPending) String() string { return proto.CompactTextString(m) }
func (*QueryAccountPending) ProtoMessage()    {}
func (*QueryAccountPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{6}
}
func (m *QueryAccountPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAccountPending.Unmarshal(m, b)
}
func (m *QueryAccountPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAccountPending.Marshal(b, m, deterministic)
}
func (dst *QueryAccountPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountPending.Merge(dst, src)
}
func (m *QueryAccountPending) XXX_Size() int {
	return xxx_messageInfo_QueryAccountPending.Size(m)
}
func (m *QueryAccountPending) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountPending.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountPending proto.InternalMessageInfo

func (m *QueryAccountPending) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *QueryAccountPending) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryAccountPending) GetSource() bool {
	if m != nil {
		return m.Source
	}
	return false
}

func (m *QueryAccountPending) GetThreshold() *wrappers.StringValue {
	if m != nil {
		return m.Threshold
	}
	return nil
}

// * query_account_pending result
type ResAccountPending struct {
	// * List of accounts, each with a list of pending blocks
	Pending              []*AccountPending `protobuf:"bytes,1,rep,name=pending,proto3" json:"pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResAccountPending) Reset()         { *m = ResAccountPending{} }
func (m *ResAccountPending) String() string { return proto.CompactTextString(m) }
func (*ResAccountPending) ProtoMessage()    {}
func (*ResAccountPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{7}
}
func (m *ResAccountPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResAccountPending.Unmarshal(m, b)
}
func (m *ResAccountPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResAccountPending.Marshal(b, m, deterministic)
}
func (dst *ResAccountPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResAccountPending.Merge(dst, src)
}
func (m *ResAccountPending) XXX_Size() int {
	return xxx_messageInfo_ResAccountPending.Size(m)
}
func (m *ResAccountPending) XXX_DiscardUnknown() {
	xxx_messageInfo_ResAccountPending.DiscardUnknown(m)
}

var xxx_messageInfo_ResAccountPending proto.InternalMessageInfo

func (m *ResAccountPending) GetPending() []*AccountPending {
	if m != nil {
		return m.Pending
	}
	return nil
}

// * Blocks per account
type AccountPending struct {
	// * The account
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// * List of blocks with details
	BlockInfo            []*AccountPendingBlockInfo `protobuf:"bytes,2,rep,name=block_info,json=blockInfo,proto3" json:"block_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AccountPending) Reset()         { *m = AccountPending{} }
func (m *AccountPending) String() string { return proto.CompactTextString(m) }
func (*AccountPending) ProtoMessage()    {}
func (*AccountPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{8}
}
func (m *AccountPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPending.Unmarshal(m, b)
}
func (m *AccountPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPending.Marshal(b, m, deterministic)
}
func (dst *AccountPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPending.Merge(dst, src)
}
func (m *AccountPending) XXX_Size() int {
	return xxx_messageInfo_AccountPending.Size(m)
}
func (m *AccountPending) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPending.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPending proto.InternalMessageInfo

func (m *AccountPending) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountPending) GetBlockInfo() []*AccountPendingBlockInfo {
	if m != nil {
		return m.BlockInfo
	}
	return nil
}

// * Information supplied for each account in query_account_pending
type AccountPendingBlockInfo struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountPendingBlockInfo) Reset()         { *m = AccountPendingBlockInfo{} }
func (m *AccountPendingBlockInfo) String() string { return proto.CompactTextString(m) }
func (*AccountPendingBlockInfo) ProtoMessage()    {}
func (*AccountPendingBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_2cfee5a72d297a47, []int{9}
}
func (m *AccountPendingBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPendingBlockInfo.Unmarshal(m, b)
}
func (m *AccountPendingBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPendingBlockInfo.Marshal(b, m, deterministic)
}
func (dst *AccountPendingBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPendingBlockInfo.Merge(dst, src)
}
func (m *AccountPendingBlockInfo) XXX_Size() int {
	return xxx_messageInfo_AccountPendingBlockInfo.Size(m)
}
func (m *AccountPendingBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPendingBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPendingBlockInfo proto.InternalMessageInfo

func (m *AccountPendingBlockInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *AccountPendingBlockInfo) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *AccountPendingBlockInfo) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*Query)(nil), "nano.api.query")
	proto.RegisterType((*Response)(nil), "nano.api.response")
	proto.RegisterType((*QueryClientConnect)(nil), "nano.api.query_client_connect")
	proto.RegisterType((*ResClientConnect)(nil), "nano.api.res_client_connect")
	proto.RegisterType((*QueryPing)(nil), "nano.api.query_ping")
	proto.RegisterType((*ResPing)(nil), "nano.api.res_ping")
	proto.RegisterType((*QueryAccountPending)(nil), "nano.api.query_account_pending")
	proto.RegisterType((*ResAccountPending)(nil), "nano.api.res_account_pending")
	proto.RegisterType((*AccountPending)(nil), "nano.api.account_pending")
	proto.RegisterType((*AccountPendingBlockInfo)(nil), "nano.api.account_pending_block_info")
	proto.RegisterEnum("nano.api.QueryType", QueryType_name, QueryType_value)
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_core_2cfee5a72d297a47) }

var fileDescriptor_core_2cfee5a72d297a47 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x6f, 0x53, 0xd3, 0x40,
	0x10, 0xc6, 0x4d, 0x29, 0xa5, 0x59, 0x2c, 0x94, 0x2b, 0x48, 0xec, 0xa0, 0x76, 0xa2, 0x8e, 0x1d,
	0xc7, 0x09, 0x0e, 0xbc, 0xf3, 0x5d, 0x89, 0x1d, 0xa6, 0xb6, 0x14, 0x3c, 0xfe, 0xf8, 0x32, 0x1e,
	0xc9, 0xd2, 0x46, 0xda, 0xbb, 0xf3, 0x92, 0xea, 0x74, 0xfc, 0x14, 0x7e, 0x00, 0xfd, 0xac, 0xce,
	0x5d, 0xd2, 0xa2, 0x15, 0x66, 0xf4, 0xdd, 0xde, 0x73, 0xbf, 0xbd, 0x7d, 0xb2, 0xbb, 0x01, 0x08,
	0x85, 0x42, 0x4f, 0x2a, 0x91, 0x0a, 0x52, 0xe6, 0x8c, 0x0b, 0x8f, 0xc9, 0xb8, 0xfe, 0x78, 0x20,
	0xc4, 0x60, 0x84, 0xbb, 0x46, 0xbf, 0x9c, 0x5c, 0xed, 0x7e, 0x55, 0x4c, 0x4a, 0x54, 0x49, 0x46,
	0xba, 0xaf, 0x61, 0xf9, 0xf3, 0x04, 0xd5, 0x94, 0xbc, 0x80, 0x62, 0x3a, 0x95, 0xe8, 0x58, 0x0d,
	0xab, 0xb9, 0xb6, 0x57, 0xf3, 0x66, 0x2f, 0x78, 0xef, 0xf5, 0xf5, 0xd9, 0x54, 0x22, 0x35, 0x80,
	0xfb, 0xd3, 0x82, 0xb2, 0xc2, 0x44, 0x0a, 0x9e, 0xe0, 0x3f, 0x67, 0x91, 0x47, 0x00, 0xa8, 0x94,
	0x50, 0x41, 0x28, 0x22, 0x74, 0x0a, 0x0d, 0xab, 0xb9, 0x41, 0x6d, 0xa3, 0xf8, 0x22, 0x42, 0xf2,
	0x14, 0x2a, 0xd9, 0xf5, 0x18, 0x93, 0x84, 0x0d, 0xd0, 0x59, 0x6a, 0x58, 0x4d, 0x9b, 0xde, 0x37,
	0xe2, 0x51, 0xa6, 0x91, 0xe7, 0xb0, 0x96, 0xbf, 0xc1, 0x52, 0x1c, 0x08, 0x35, 0x75, 0x8a, 0x86,
	0xca, 0x52, 0xfd, 0x5c, 0x74, 0x53, 0xd8, 0x34, 0x9f, 0x14, 0x84, 0xa3, 0x18, 0x79, 0x1a, 0x84,
	0x82, 0x73, 0x0c, 0x53, 0xf2, 0x04, 0x56, 0x99, 0x8c, 0x83, 0x2f, 0xa8, 0x92, 0x58, 0x70, 0x63,
	0xb9, 0x42, 0x81, 0xc9, 0xf8, 0x22, 0x53, 0x88, 0x0b, 0x15, 0x0d, 0xe4, 0x69, 0x71, 0x64, 0x6c,
	0xda, 0x54, 0x67, 0xf9, 0x46, 0xeb, 0x44, 0x64, 0x1b, 0x56, 0x34, 0x73, 0x8d, 0xd3, 0xdc, 0x62,
	0x89, 0xc9, 0xb8, 0x8b, 0x53, 0xf7, 0xbb, 0x05, 0x44, 0x61, 0xf2, 0xdf, 0x45, 0x5f, 0x01, 0xe1,
	0x22, 0xc2, 0x19, 0x11, 0x8c, 0xd9, 0x27, 0xa1, 0x4c, 0xe5, 0x0a, 0xad, 0xea, 0x9b, 0x1c, 0x3c,
	0xd2, 0xfa, 0x5f, 0xb4, 0x64, 0x69, 0x38, 0x34, 0x4e, 0xfe, 0xa4, 0x4f, 0xb4, 0xee, 0xee, 0x00,
	0x64, 0x9d, 0x90, 0x31, 0x1f, 0x90, 0x35, 0x28, 0xc4, 0x51, 0xee, 0xa0, 0x10, 0x47, 0x6e, 0xdd,
	0xcc, 0xf1, 0xf6, 0xbb, 0x1f, 0x16, 0x6c, 0x65, 0xa9, 0x2c, 0x0c, 0xc5, 0x84, 0xa7, 0x81, 0x44,
	0x1e, 0x69, 0xb2, 0x0e, 0xe5, 0x5c, 0x4a, 0x1c, 0xab, 0xb1, 0xd4, 0xb4, 0xe9, 0xfc, 0x4c, 0x36,
	0x61, 0xd9, 0x44, 0xc6, 0x7e, 0x91, 0x66, 0x07, 0xf2, 0x00, 0x4a, 0x89, 0x98, 0xa8, 0x30, 0x1b,
	0x6a, 0x99, 0xe6, 0x27, 0xf2, 0x06, 0xec, 0x74, 0xa8, 0x30, 0x19, 0x8a, 0x51, 0x64, 0x26, 0xb9,
	0xba, 0xb7, 0xe3, 0x65, 0xeb, 0xea, 0xcd, 0xd6, 0xd5, 0x3b, 0x4d, 0x55, 0xcc, 0x07, 0x17, 0x6c,
	0x34, 0x41, 0x7a, 0x83, 0xbb, 0xef, 0xa0, 0xa6, 0xbd, 0x2f, 0x9a, 0xdb, 0x87, 0x95, 0x3c, 0x34,
	0xde, 0x56, 0xf7, 0x1e, 0xde, 0x6c, 0xe4, 0x02, 0x4b, 0x67, 0xa4, 0x2b, 0x61, 0x7d, 0xf1, 0x1d,
	0x07, 0x56, 0x72, 0xc9, 0xf4, 0xc4, 0xa6, 0xb3, 0x23, 0xf1, 0x01, 0x2e, 0x47, 0x22, 0xbc, 0x0e,
	0x62, 0x7e, 0x25, 0x9c, 0x82, 0x29, 0xf2, 0xec, 0xce, 0x22, 0xc1, 0x0d, 0x4b, 0x6d, 0x13, 0x77,
	0xf8, 0x95, 0x70, 0x3f, 0x42, 0xfd, 0x6e, 0x90, 0x10, 0x28, 0x0e, 0x59, 0x32, 0xcc, 0x2b, 0x9b,
	0x58, 0xf7, 0x90, 0x8d, 0xe7, 0xad, 0xd5, 0x5b, 0x37, 0xbe, 0xa5, 0xb7, 0xf6, 0xac, 0xb7, 0x2f,
	0xbf, 0x81, 0x3d, 0xff, 0x03, 0x09, 0x40, 0xe9, 0xbc, 0xdf, 0x3d, 0xfe, 0xd0, 0xaf, 0xde, 0x23,
	0x5b, 0xb0, 0x41, 0xdb, 0x87, 0x9d, 0xd3, 0xb3, 0x36, 0x0d, 0xfc, 0x56, 0xaf, 0x77, 0xd0, 0xf2,
	0xbb, 0x55, 0x8b, 0x94, 0xa1, 0x78, 0xd2, 0xe9, 0x1f, 0x56, 0x0b, 0xa4, 0x06, 0xeb, 0x2d, 0xdf,
	0x3f, 0x3e, 0xef, 0x9f, 0x05, 0x07, 0xad, 0x5e, 0xab, 0xef, 0xb7, 0xab, 0x4b, 0x64, 0x1b, 0x6a,
	0x73, 0xb1, 0x77, 0xec, 0x77, 0x03, 0x13, 0x57, 0x8b, 0xbf, 0xd3, 0x27, 0xed, 0xfe, 0x5b, 0xfd,
	0xc4, 0xf2, 0x65, 0xc9, 0x4c, 0x6f, 0xff, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0x65, 0x83,
	0xb5, 0x92, 0x04, 0x00, 0x00,
}
